language: python

python:
#  - "3.6"
  - "3.7"
#  - "3.8"
  - "3.9"

install:
  - pip install -r src/requirements.txt
  - pip install codecov pytest-cov flake8 flake8-docstrings black

script:
  - echo "Running checks on repository"
  - bash resources/releng/chcek_repository.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
