# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aura_dataprep.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aura_dataprep.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x61ura_dataprep.proto\"\x15\n\x06OutDir\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t\"\x15\n\x06\x45\x64\x66\x44ir\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t21\n\x0c\x41uraDataprep\x12!\n\rprepareEdfDir\x12\x07.EdfDir\x1a\x07.OutDirb\x06proto3'
)




_OUTDIR = _descriptor.Descriptor(
  name='OutDir',
  full_name='OutDir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='OutDir.dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=44,
)


_EDFDIR = _descriptor.Descriptor(
  name='EdfDir',
  full_name='EdfDir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='EdfDir.dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['OutDir'] = _OUTDIR
DESCRIPTOR.message_types_by_name['EdfDir'] = _EDFDIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OutDir = _reflection.GeneratedProtocolMessageType('OutDir', (_message.Message,), {
  'DESCRIPTOR' : _OUTDIR,
  '__module__' : 'aura_dataprep_pb2'
  # @@protoc_insertion_point(class_scope:OutDir)
  })
_sym_db.RegisterMessage(OutDir)

EdfDir = _reflection.GeneratedProtocolMessageType('EdfDir', (_message.Message,), {
  'DESCRIPTOR' : _EDFDIR,
  '__module__' : 'aura_dataprep_pb2'
  # @@protoc_insertion_point(class_scope:EdfDir)
  })
_sym_db.RegisterMessage(EdfDir)



_AURADATAPREP = _descriptor.ServiceDescriptor(
  name='AuraDataprep',
  full_name='AuraDataprep',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=69,
  serialized_end=118,
  methods=[
  _descriptor.MethodDescriptor(
    name='prepareEdfDir',
    full_name='AuraDataprep.prepareEdfDir',
    index=0,
    containing_service=None,
    input_type=_EDFDIR,
    output_type=_OUTDIR,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AURADATAPREP)

DESCRIPTOR.services_by_name['AuraDataprep'] = _AURADATAPREP

# @@protoc_insertion_point(module_scope)
