# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import aura_ml_trainer_pb2 as aura__ml__trainer__pb2


class AuraMlTrainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.startTraining = channel.unary_unary(
                '/AuraMlTrainer/startTraining',
                request_serializer=aura__ml__trainer__pb2.DataDir.SerializeToString,
                response_deserializer=aura__ml__trainer__pb2.TrainingStatus.FromString,
                )


class AuraMlTrainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def startTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuraMlTrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'startTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.startTraining,
                    request_deserializer=aura__ml__trainer__pb2.DataDir.FromString,
                    response_serializer=aura__ml__trainer__pb2.TrainingStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuraMlTrainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuraMlTrainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def startTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuraMlTrainer/startTraining',
            aura__ml__trainer__pb2.DataDir.SerializeToString,
            aura__ml__trainer__pb2.TrainingStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
