# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aura_ml_trainer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aura_ml_trainer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x61ura_ml_trainer.proto\"\x16\n\x07\x44\x61taDir\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t\"P\n\x0eTrainingStatus\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x01\x12\x17\n\x0fvalidation_loss\x18\x02 \x01(\x01\x12\x13\n\x0bstatus_text\x18\x03 \x01(\t2;\n\rAuraMlTrainer\x12*\n\rstartTraining\x12\x08.DataDir\x1a\x0f.TrainingStatusb\x06proto3'
)




_DATADIR = _descriptor.Descriptor(
  name='DataDir',
  full_name='DataDir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='DataDir.dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=47,
)


_TRAININGSTATUS = _descriptor.Descriptor(
  name='TrainingStatus',
  full_name='TrainingStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='TrainingStatus.accuracy', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='validation_loss', full_name='TrainingStatus.validation_loss', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_text', full_name='TrainingStatus.status_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['DataDir'] = _DATADIR
DESCRIPTOR.message_types_by_name['TrainingStatus'] = _TRAININGSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataDir = _reflection.GeneratedProtocolMessageType('DataDir', (_message.Message,), {
  'DESCRIPTOR' : _DATADIR,
  '__module__' : 'aura_ml_trainer_pb2'
  # @@protoc_insertion_point(class_scope:DataDir)
  })
_sym_db.RegisterMessage(DataDir)

TrainingStatus = _reflection.GeneratedProtocolMessageType('TrainingStatus', (_message.Message,), {
  'DESCRIPTOR' : _TRAININGSTATUS,
  '__module__' : 'aura_ml_trainer_pb2'
  # @@protoc_insertion_point(class_scope:TrainingStatus)
  })
_sym_db.RegisterMessage(TrainingStatus)



_AURAMLTRAINER = _descriptor.ServiceDescriptor(
  name='AuraMlTrainer',
  full_name='AuraMlTrainer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=131,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='startTraining',
    full_name='AuraMlTrainer.startTraining',
    index=0,
    containing_service=None,
    input_type=_DATADIR,
    output_type=_TRAININGSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AURAMLTRAINER)

DESCRIPTOR.services_by_name['AuraMlTrainer'] = _AURAMLTRAINER

# @@protoc_insertion_point(module_scope)
