# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import aura_dataprep_pb2 as aura__dataprep__pb2


class AuraDataprepStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.prepareEdfFile = channel.unary_unary(
            "/AuraDataprep/prepareEdfFile",
            request_serializer=aura__dataprep__pb2.EdfFile.SerializeToString,
            response_deserializer=aura__dataprep__pb2.DataFile.FromString,
        )


class AuraDataprepServicer(object):
    """Missing associated documentation comment in .proto file."""

    def prepareEdfFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AuraDataprepServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "prepareEdfFile": grpc.unary_unary_rpc_method_handler(
            servicer.prepareEdfFile,
            request_deserializer=aura__dataprep__pb2.EdfFile.FromString,
            response_serializer=aura__dataprep__pb2.DataFile.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "AuraDataprep", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AuraDataprep(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def prepareEdfFile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/AuraDataprep/prepareEdfFile",
            aura__dataprep__pb2.EdfFile.SerializeToString,
            aura__dataprep__pb2.DataFile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
