# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import edf_databroker_train_pb2 as edf__databroker__train__pb2


class EdfDatabrokerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_next_edf_dir = channel.unary_unary(
                '/EdfDatabroker/get_next_edf_dir',
                request_serializer=edf__databroker__train__pb2.Empty.SerializeToString,
                response_deserializer=edf__databroker__train__pb2.EdfDir.FromString,
                )


class EdfDatabrokerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_next_edf_dir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdfDatabrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_next_edf_dir': grpc.unary_unary_rpc_method_handler(
                    servicer.get_next_edf_dir,
                    request_deserializer=edf__databroker__train__pb2.Empty.FromString,
                    response_serializer=edf__databroker__train__pb2.EdfDir.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EdfDatabroker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EdfDatabroker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_next_edf_dir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EdfDatabroker/get_next_edf_dir',
            edf__databroker__train__pb2.Empty.SerializeToString,
            edf__databroker__train__pb2.EdfDir.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
