pipeline {  

  agent any

  stages {

    stage('Checkout') { // Checkout (git clone ...) the projects repository
      steps {
        checkout scm
      }
    }
    stage('Setup') { // Install any dependencies you need to perform testing
      steps {
        script {
          sh """
          PYENV_HOME=$WORKSPACE/.pyenv/

          # Delete previously built virtualenv
          if [ -d $PYENV_HOME ]; then
              rm -rf $PYENV_HOME
          fi

          # Create virtualenv and install necessary packages
          virtualenv --no-site-packages $PYENV_HOME
          . $PYENV_HOME/bin/activate
          pip install --quiet nosexcover
          pip install --quiet pylint
          pip install --quiet $WORKSPACE/  # where your setup.py lives
          nosetests --with-xcoverage --with-xunit --cover-package=aibricks --cover-erase
          pylint -f parseable aibricks/ | tee pylint.out
          cd aibricks
          pip install -r requirements.txt
          """
        }
      }
    }
    stage('Linting') { // Run pylint against your code
      steps {
        script {
          sh """
          pylint **/*.py
          """
        }
      }
    }
    stage('Unit Testing') { // Perform unit testing
      steps {
        script {
          sh """
          pytest aibricks/ -s tests/unit
          """
        }
      }
    }
  }
}
