version: '3.3'

services:

  aura_ml_trainer:
    image: bbaldassari/aura_ml_trainer:latest
    build: aura_ml_trainer/
    container_name: aura-ml-trainer
    volumes:
      - ${DATA_DIR}/:/data
    command: ["bash", "/aura/scripts/create_ml_and_train.sh", "/data/out", "/data/model"]


volumes:
    edf-storage:
